### ISSUE TITLE
Feature set per chip needs to still be documented but was removed during major restructuring

### ISSUE THREAD

**Issue by lonerzzz** [kuba2k2/libretiny#117]
Prior to the update and restructure, you included the Arduino/ESP compatibilities per chip on the main page. After refactoring, this does not exist but such a map should be provided in some form somewhere so that people understand what capabilities are in place.

**Comment by kuba2k2** [comment]
I've temporarily removed the table, because it has been confusing and hasn't been updated for a long time. It will be re-added at some point though.

**Comment by kuba2k2** [comment]
Added back.
