### ISSUE TITLE
default state on reboot or power loss state control?

### ISSUE THREAD

**Issue by dasb00ter** [kuba2k2/libretiny#141]
Not sure this is the right place to ask. I have a bulb I am looking at that is on becomes unavailable and when I see it returning its off when its supposed to be on for night illumination. I am just trying to make sense of the behavior...it doesn't look like wifi should be a problem. A quick google search didnt turn anything up on libretiny and default power on states.

**Comment by kuba2k2** [comment]
This is an ESPHome feature, refer to the ESPHome docs for help.
