### ISSUE TITLE
Failed to start task

### ISSUE THREAD

**Issue by herobrine30396** [kuba2k2/libretiny#151]
I keep getting this error in the serial monitor, and the AsyncTcpWebserver doesn't work:
```
E [      5.316] failed to start task
E [      5.316] failed to start task
E [      5.316] failed to start task
```

**Comment by herobrine30396** [comment]
It's a problem with the memory allocation of AsyncTcpWebserver. I created a fork that decreases the memory allocated to the library, and now it works!

**Comment by herobrine30396** [comment]
I have another problem now. There's some issue that stops `LwIPUDP::beginMulticast` so that I get this in the serial monitor:
`E [      5.322] could not join igmp: 125`. Any help?

**Comment by kuba2k2** [comment]
Yes, the task failing to start is nearly always because of lack of memory. I don't know which library are you using, but LT's fork adds another #define that decreases the stack size of the task.
About the IGMP issue, check the errno codes for code 125. From a quick look in Google it might be "too many links" or "cancelled".

**Comment by Cossid** [comment]
> I have another problem now. There's some issue that stops `LwIPUDP::beginMulticast` so that I get this in the serial monitor: `E [ 5.322] could not join igmp: 125`. Any help?

I recently ran into the same issue, and the problem appears lwip wasn't fully initialized yet.  I added a delay before attempting beginMulticast (in this case, waiting until esphome's setup function had completed), and it worked fine afterwards.

**Comment by herobrine30396** [comment]
Oh, okay. Will try that, but right now, I'm not able to upload anything to my board to test it. I've created a separate issue regarding that

**Comment by Phil1pp** [comment]
> I have another problem now. There's some issue that stops `LwIPUDP::beginMulticast` so that I get this in the serial monitor: `E [ 5.322] could not join igmp: 125`. Any help?

Did you ever get that resolved?
I am facing the same issue.
