### ISSUE TITLE
pinscan

### ISSUE THREAD

**Issue by bonuzzz** [kuba2k2/libretiny#8]
when I choose Read one pin continuously in digital pins and enter for example 3 or D3 of other number, I always see:
`Pin D0 state:`

ps: I can't get working pinscan over uart. I see board logs only there. I connect through telnet.
After  Realtime readout of all pins in digital pins I have to reboot board because it doesn't respond on q key and I don't see any answer there (I'm not sure if I should see anything here not touching any buttons on switch)

**Comment by kuba2k2** [comment]
Yes, for some reason, realtime readout doesn't work on telnet. I'm not sure about the D0 issue, maybe it's incompatible with the terminal app you're using. Try PuTTY.

"I see board logs only there" what logs? On which uart (1 or 2)? Did you change the default port?

If you enable telnet in PinScan, it disables uart completely.
